global:
  scrape_interval: 5s
  external_labels:
    monitor: 'node'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.16.55.85:9090'] ## IP addr of the docker lan 01 [prometheus]
        
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['172.16.55.85:9100'] ## IP addr of the lan 01 [Node-Exporter]

